[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/containerd/containerd"
  version = "1.3.2"

[[constraint]]
  name = "github.com/morikuni/aec"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  name = "github.com/alexellis/k3sup"
  version = "0.9.3"

[[constraint]]
  name = "github.com/alexellis/go-execute"
  version = "0.4.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.3"

[[constraint]]
  name = "github.com/openfaas/faas"
  version = "0.18.7"

[[constraint]]
  name = "github.com/sethvargo/go-password"
  version = "0.1.3"

[[constraint]]
  branch = "master"
  name = "github.com/containerd/go-cni"

[[constraint]]
  name = "github.com/openfaas/faas-provider"
  version = "v0.15.1"

[[constraint]]
  name = "github.com/docker/cli"
  version = "19.3.5"
