[[constraint]]
  name = "github.com/containerd/containerd"
  version = "1.3.2"

[[constraint]]
  name = "github.com/morikuni/aec"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  name = "github.com/alexellis/k3sup"
  version = "0.7.1"

[[constraint]]
  name = "github.com/alexellis/go-execute"
  version = "0.3.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/sethvargo/go-password"
  version = "0.1.3"

[[constraint]]
  branch = "master"
  name = "github.com/containerd/go-cni"

[[constraint]]
  name = "github.com/openfaas/faas-provider"
  version = "0.14.0"

[[constraint]]
  branch = "master"
  name = "github.com/shurcooL/vfsgen"
